### ISSUE TITLE
Atom v1.13 deprecation warning

### ISSUE THREAD

**Issue by ghost** [michardy/contrast-syntax#1]
I am getting a deprecation warning after installing the **constrast-ui** and **contrast-syntax** themes. The error states:

```
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--...
```

**Comment by michardy** [comment]
I have been a little bit busy and am no longer using atom but I will try to fix the problem.  
- [x] `:host` is used twice in contrast-syntax and not at all in contrast-ui.  
- [x] It appears `::shadow` is not in use in any of my code.  
- [x] I need to identify all the syntax selectors and append `syntax--` to them (there should be about 90 of them).  
- [ ] test

**Comment by ghost** [comment]
Thanks for the reply Michael. I appreciate you updating the projects despite no longer using Atom. In terms of available contrast themes, I think you have published the best ones.

Q? If you are not using Atom, what are you using for a code editor now? Have you migrated to VS Code?

**Comment by michardy** [comment]
Fixes taking place on [michardy-DOM-shadowing-fix](https://github.com/michardy/contrast-syntax/tree/michardy-DOM-shadowing-fix) branch.  I have not yet found all the syntax selectors although I have a nice [list](https://github.com/fedu/fedu-syntax/issues/1) from another project.

Currently I am using these programming environments (If you can call them that):
Windows C++:
Visual Studio Community

Windows Python:
IDLE

Windows other:
Notepad++

Linux:
nano&bash

I should probably be more consistent.

**Comment by michardy** [comment]
Updated syntax selectors: 18e7a850881359a7271529e7298d1fe4ee921967

**Comment by ghost** [comment]
Thanks Michael, I am sorry this was such an tedious change.

**Comment by michardy** [comment]
Fixed contrast syntax
